<script src="/lib/jquery/ui/ui/animatedcollapse.js">
  /***********************************************
  * Animated Collapsible DIV v2.4- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
  * This notice MUST stay intact for legal use
  * Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more
  ***********************************************/

</script>
<script type="text/javascript" language="javascript">
  function hideNoCollapse() {
  jQuery("#nocollapse_all_button").hide();
  jQuery("#collapse_all_button").show();
  }

  function hideCollapse() {
  jQuery("#nocollapse_all_button").show();
  jQuery("#collapse_all_button").hide();
  }

</script>

